services:
  db:
    image: postgres:17
    env_file:
      - .env.production
    ports:
      - "5433:5432"
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bmm_prod

  frontend:
    build:
      dockerfile: Dockerfile.fe
      target: frontend
      args:
        - VITE_API_ENDPOINT=${VITE_API_ENDPOINT}
    ports:
      - "5174:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bmm_prod

  db_migration:
    build:
      dockerfile: Dockerfile.be
      target: db_migration
    env_file:
      - .env.production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bmm_prod

  backend:
    build:
      dockerfile: Dockerfile.be
      target: backend
    env_file:
      - .env.production
    ports:
      - "3001:3000"
    depends_on:
      db_migration:
        condition: service_completed_successfully
    networks:
      - bmm_prod

volumes:
  db_data_prod:

networks:
  bmm_prod:
