FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm i -g pnpm@10.6.3

ARG VITE_API_ENDPOINT

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app
ENV VITE_API_ENDPOINT=ARG
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run -r build
RUN pnpm deploy --legacy --filter=frontend --prod /prod/frontend

FROM base AS frontend
COPY --from=build /prod/frontend /prod/frontend
WORKDIR /prod/frontend
EXPOSE 5173
RUN npm i -g serve@14
CMD [ "serve" ]
