[workspace]
members = ["xtask"]

[package]
name = "backend"
version = "0.0.0"
edition = "2024"

[workspace.dependencies]
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "postgres",
    "uuid",
    "time",
] }
anyhow = "1.0.98"
dotenvy = "0.15.7"
time = { version = "0.3.41", features = ["macros", "serde-well-known"] }
async-trait = "0.1.88"
garde = { version = "0.22.0", features = ["full"] }
tower-http = { version = "0.6.6", features = ["cors"] }
serde_json = { version = "1.0.141" }
regex = "1.11.1"

[dependencies]
axum.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
sqlx.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
time.workspace = true
async-trait.workspace = true
garde.workspace = true
tower-http.workspace = true
serde_json.workspace = true
regex.workspace = true


[dev-dependencies]
tower = { version = "0.5.2", features = ["full"] }
http-body-util = "0.1.3"
